"""
AutoPy 命令模块

提供 CDP 命令、页面指令（Instruction/ElementClass）与 HTTP 命令（含比特浏览器），供 Browser 发往节点。
"""

from .cdp import (
    CdpCommand,
    CdpConnectCommand,
    CdpDisconnectCommand,
    ListTargetsCommand,
    ExecuteJavascriptCommand,
    TakeElementScreenshotCommand,
    SendCommandCommand,
    GrepSourceCommand,
    GetNetworkLogsCommand,
    InitNetworkLogsCommand,
    CloseNetworkLogsCommand,
    GetConsoleLogsCommand,
    InitConsoleLogsCommand,
    CloseConsoleLogsCommand,
    CreateTabAndNavigateCommand,
    UpdateNodeNameCommand,
    CloseTabCommand,
)
from .instruction import (
    ElementClass,
    Instruction,
    Instructions,
    NavigateInstruction,
    ExecuteScriptInstruction,
    FindElementInstruction,
    InputInstruction,
    KeyboardInstruction,
    MouseInstruction,
    GetAttributeInstruction,
    SetAttributeInstruction,
    ScreenshotInstruction,
    WaitInstruction,
    GetUrlInstruction,
    ActivateTabInstruction,
)
from .http import (
    HttpCommand,
    HttpBitBrowserOpenCommand,
    HttpBitBrowserCloseCommand,
    HttpBitBrowserListCommand,
    HttpBitBrowserResetCommand,
    HttpBitBrowserAliveCommand,
)

__all__ = [
    "CdpCommand",
    "CdpConnectCommand",
    "CdpDisconnectCommand",
    "ListTargetsCommand",
    "ExecuteJavascriptCommand",
    "TakeElementScreenshotCommand",
    "SendCommandCommand",
    "GrepSourceCommand",
    "GetNetworkLogsCommand",
    "InitNetworkLogsCommand",
    "CloseNetworkLogsCommand",
    "GetConsoleLogsCommand",
    "InitConsoleLogsCommand",
    "CloseConsoleLogsCommand",
    "CreateTabAndNavigateCommand",
    "UpdateNodeNameCommand",
    "CloseTabCommand",
    "ElementClass",
    "Instruction",
    "Instructions",
    "NavigateInstruction",
    "ExecuteScriptInstruction",
    "FindElementInstruction",
    "InputInstruction",
    "KeyboardInstruction",
    "MouseInstruction",
    "GetAttributeInstruction",
    "SetAttributeInstruction",
    "ScreenshotInstruction",
    "WaitInstruction",
    "GetUrlInstruction",
    "ActivateTabInstruction",
    "HttpCommand",
    "HttpBitBrowserOpenCommand",
    "HttpBitBrowserCloseCommand",
    "HttpBitBrowserListCommand",
    "HttpBitBrowserResetCommand",
    "HttpBitBrowserAliveCommand",
]